version: "3.9"

services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./app:/app # Mount only the app folder so that manage.py is at /app/manage.py
    env_file:
      - .env
    depends_on:
      - db
      - redis

  db:
    image: postgres:13-alpine
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - dev-db-data:/var/lib/postgresql/data

  redis:
    image: redis:alpine
    ports:
      - "6379:6379"

  formatter:
    build:
      context: .
      args:
        - DEV=true
    volumes:
      - ./app:/app # Mount only the app folder so format.sh (if inside app) is available
    command: sh /app/format.sh
    env_file:
      - .env

volumes:
  dev-db-data:
