name: Checks

on: [push]

jobs:
  test-lint:
    name: Test and Lint
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up environment variables
      run: |
        echo "DB_HOST=${{ secrets.DB_HOST }}" >> .env
        echo "DB_NAME=${{ secrets.DB_NAME }}" >> .env
        echo "DB_USER=${{ secrets.DB_USER }}" >> .env
        echo "DB_PASSWORD=${{ secrets.DB_PASSWORD }}" >> .env
        echo "REDIS_URL_SSM_NAME=${{ secrets.REDIS_URL_SSM_NAME }}" >> .env
        echo "REDIS_URL=${{ secrets.REDIS_URL }}" >> .env
        echo "DJANGO_ENV=${{ secrets.DJANGO_ENV }}" >> .env
        echo "COGNITO_CLIENT_ID_SSM_PATH=${{ secrets.COGNITO_CLIENT_ID_SSM_PATH }}" >> .env
        echo "AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}" >> .env
        echo "AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> .env
        echo "AWS_DEFAULT_REGION=${{ secrets.AWS_DEFAULT_REGION }}" >> .env

    - name: Build Docker images
      run: docker compose build

    - name: Test
      run: docker compose run --rm app sh -c "python manage.py wait_for_db && python manage.py test"

    - name: Lint
      run: docker compose run --rm app sh -c "flake8"
